spring.application.name=fitness-monolith

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/fitness_tracker}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:mahesh}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=update

# Hibernate 6 auto-detects MySQL dialect (no need to set explicitly)

# Optional (for learning & debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
